<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5EVK54D" failures="1" tests="2" name="Test" time="16.628" errors="0" timestamp="2023-06-21T20:27:34 IST">
  <testcase classname="testngdiscussion.ParallelClassExecution1" name="sliderValidation" time="12.819"/>
  <testcase classname="testngdiscussion.ParallelClassExecution2" name="validateHover" time="16.532">
    <failure type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException
at testngdiscussion.ParallelClassExecution2.validateHover(ParallelClassExecution2.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- validateHover -->
</testsuite> <!-- Test -->
